### ISSUE TITLE
Work with Raspberry Pi?

### ISSUE THREAD

**Issue by billc2013** [nationalparkservice/hobo-py#5]
Hello!  I was delighted to see this project!  Does it work for Raspberry Pi?  The Pi recognizes the HOBO Base Station that I have but I am stumped on next steps to get the Hobo to download data to the Pi.  Any thoughts?  Thank you very much!

**Comment by riggsd** [comment]
This library is for working with data exported from HOBO data loggers; it does not communicate directly with the data loggers themselves.

**Comment by billc2013** [comment]
Thank you!  Do you know anyone working on connecting Raspberry Pi's with Hobo data loggers?

**Comment by riggsd** [comment]
I do not.

As far as I'm aware, Onset doesn't publish a wire protocol for communicating directly with Hobo data loggers, and their proprietary software is required for offloading the data. That's why this library exclusively processes _exported_ Hobo data.

**Comment by billc2013** [comment]
Received!  Thanks for responding!
